// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirpWithID = `-- name: DeleteChirpWithID :exec
DELETE FROM chirps
WHERE id = $1
`

func (q *Queries) DeleteChirpWithID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChirpWithID, id)
	return err
}
