// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_users.sql

package database

import (
	"context"
)

const emptyUsers = `-- name: EmptyUsers :exec
DELETE FROM users
`

func (q *Queries) EmptyUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, emptyUsers)
	return err
}
