// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user_pwd_email_from_token.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserPwdEmailByToken = `-- name: UpdateUserPwdEmailByToken :one
UPDATE users
SET email = $1, hashed_password = $2
WHERE id = $3  --ID get from checking JWT Token before parsing 
RETURNING email
`

type UpdateUserPwdEmailByTokenParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) UpdateUserPwdEmailByToken(ctx context.Context, arg UpdateUserPwdEmailByTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, updateUserPwdEmailByToken, arg.Email, arg.HashedPassword, arg.ID)
	var email string
	err := row.Scan(&email)
	return email, err
}
