// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user_membership.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserMembershipByID = `-- name: UpdateUserMembershipByID :exec
UPDATE users
SET is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) UpdateUserMembershipByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserMembershipByID, id)
	return err
}
